apiVersion: v1
kind: Service
metadata:
  name: dudidemo
  labels:
    service: dudidemo
spec:
  selector:
    service: dudidemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP